name: Create Jira Task

on:
  issues:
    types: [opened]

jobs:
  create-jira-task:
    runs-on: ubuntu-latest
    steps:
      - name: Create Jira Issue
        uses: valeriobelli/jira-gh-action@v1.0.0
        with:
          jira-url: ${{ secrets.JIRA_BASE_URL }}
          jira-user: ${{ secrets.JIRA_USER_EMAIL }}
          jira-token: ${{ secrets.JIRA_API_TOKEN }}
          project-id: CPG
          issue-type: Task
          summary: "${{ github.event.issue.title }}"
          description: "GitHub Issue: ${{ github.event.issue.html_url }}\n\n${{ github.event.issue.body }}"