name: Create Jira Task

on:
  issues:
    types: [opened]

jobs:
  create-jira-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Create Jira Issue
        id: create
        uses: atlassian/jira-create-issue-action@v1
        with:
          project: CPG
          issuetype: Task
          summary: "${{ github.event.issue.title }}"
          description: |
            GitHub Issue: ${{ github.event.issue.html_url }}
            
            ${{ github.event.issue.body }}
          fields: '{"labels": ["github-issue"]}'
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          
      - name: Log Created Issue
        if: steps.create.outputs.issue
        run: echo "Created issue ${{ steps.create.outputs.issue }}" 